Feature/updateDataCenterAPI
icgc-argo/program-service pull request #428
Opened 2023-10-11 15:45 UTC by Azher2Ali

Implemented a PATCH endpoint for partial updates of Data Centers, ensuring that only provided values are modified and handling immutable properties appropriately. The endpoint returns a JSON object with the updated Data Center. Error handling includes returning a 400 error for invalid properties and a 404 error if the provided short name is not found. Authentication restricts access to DCC Admins and RDPC Admins with proper permissions, and unit testing was conducted for validation.

2023-11-07 16:36 UTC, joneubank requested changes
Mostly good stuff, requesting one easy fix on request paths, plus one change to clean up the request bodies for create vs update requests.

2023-11-07 16:36 UTC, joneubank commented on src/main/java/org/icgc/argo/program_service/services/ProgramServiceFacade.java
> +  @Transactional
Good idea, very nice.

2023-11-08 17:17 UTC, Azher2Ali commented on src/main/java/org/icgc/argo/program_service/controller/DataCenterController.java
> +  @GetMapping(value = "/datacenters/{datacenter_short_name}/programs")
Removed datacenter from API path

2023-11-08 17:18 UTC, Azher2Ali commented on src/main/java/org/icgc/argo/program_service/model/dto/DataCenterRequestDTO.java
> +}
Validating the create request through ValidationService, therefore we can still use the same request DTO for create and update.

2023-11-08 19:16 UTC, joneubank approved these changes
This looks clean. Thanks for the updates!

2023-11-08 20:08 UTC, merged